### ISSUE TITLE
1.7.0 Known Issues

### ISSUE THREAD

**Issue by lemmy** [tlaplus/tlaplus#453]
- [x] Bump version numbers to 1.7.1 following yesterday's release of 1.7.0. e3220f2
- [x] Multi-line trace expressions result in SANY parser error  defe0c74915b1c27c6af2fb55c8163f3574c8918
- [x] Delete old/outdated files when syncing Github artifacts to 4897510
- [x] Notarize macOS build of Toolbox automatically. 98d9830
- [x] Disambiguate for Java 13+ 5e104bc
- [x] Upstream removed old builds. Consume from our own "mirror" that a748f05
- [x] TLC shows no error trace on violated TLC!Assert https://github.com/tlaplus/tlaplus/issues/461 19757bd
- [x] New Java 11 dependency, Java 8 causes "NoSuchMethodError: String.strip()" #462 e6bd13e
- [x] Dot visualization (graphviz) fails due to invalid character `!` when spec uses instantiation #452 a8fc5b1
- [x] PlusCal transpiler hangs on parsing an incorrect label #358 198d3fc ad34fc9
- [x] Toolbox fails to detect existing checkpoints #469 a754d8d
- [x] TLC process can hang indefinitely after finish message with '-generateSpecTE' ffaa8bb62dd0f0f97fd7edbcc7a741798c5d166b
- [x] CHECK_DEADLOCK keyword interpreted as value ab047b129987897b5112363b83dff2b4ca80e017
- [x] TLCSet and TLCGet broken in simulation mode. cc83fe0 (needed trivial merge of SimulationWorker.java)
- [x] PlusCal divergence detection does not honor the module end marker b7357280cdec8f418abf154a58b6a7120d3ef453 e434e139adebf73ed8f9470117031f1ad4b749df 7c61d1a f1cf514 d11e08d 9f0144e 3b7dabe
- [x] Simulation mode ignores ASSUMPTIONS 51b5ef4 cca008f
- [x] State of checkbuttons is indistinguishable and error marker barely visible on Linux   https://github.com/tlaplus/tlaplus/issues/472 dc67692e17cb75866e7005358255d9849870fc4a a3359e5948e4ef67a641142c5c107801a82b9e8a 65ada5dcdfad33626aa5017b35ffa187497f7a9e
- [x] Back to state missing for lasso error trace found by simulation #497 7610d3f
- [x] Copy doc/ folder to INRIA machine. 6a1ac6c
- [x] Do not upload/rsync *unsigned* TLAToolbox macOS zip from Linux/Ubuntu 0e33c51
- [x] AtNode does not show up in (dot) graph output of semantic explorer 52f3b01
- [x] Replace custom implementation of (heap) sort in TeX with java.utils.Arrays.sort https://github.com/tlaplus/tlaplus/issues/539 8b52d23
- [x] Toolbox intermittently shows no error trace on an invariant violation https://github.com/tlaplus/tlaplus/issues/538 10cae87
- [x] End support for liveness checking and multiple workers in DFID mode because both features are unreliable https://github.com/tlaplus/tlaplus/issues/548 https://github.com/tlaplus/tlaplus/issues/544 
e3f1d24 (comes before 10cae87) 0faf578 f01d925
- [x] TLC startup banner reports bogus date: `TLC2 Version 2.15 of Day Month 20?? (rev: eb3ff99)` 5c01faf61fb209f2f0d4fd38a6493878454c2724

More upcoming changes are listed at https://github.com/tlaplus/tlaplus/milestone/9

Issues above that are marked as done have already been fixed in the [nightly build](https://nightly.tlapl.us/products/).
